name: Motech
favicon: null
layout_spectrum: 0.14183
typography_spectrum: 0.3387
title: The Motech Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0e7ac'
    - '#ffffff'
    - '#8490a8'
    - '#1b65ac'
    - '#c6c6a9'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.05048867780715227
  rhythmicContrast: 0.75
purpose: []
