name: Motech
favicon: null
layout_spectrum: 0.2083584840875119
typography_spectrum: 0.2077280271332711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6872018398717046
  lightness: 0.16894380538724363
  saturation: 0.05048867780715227
  rhythmicContrast: 0.3964155151043087
purpose: []
